-- GENERATED by scripts/build-db-migration.mjs — do not edit by hand.
-- Source of truth: supabase/tables/*.sql (applied in file-name order).
-- Reference only: databases are built from supabase/migrations/.

-- ===== 00_helpers.sql =====

-- Shared helpers used by the table files that follow.
--
-- The room and social helpers are plpgsql on purpose: unlike `language sql`, their bodies
-- aren't resolved until they run, so tables created earlier (profiles, rooms)
-- can use them in policies before `room_members` / `follows` exist.

-- Server-owned `updated_at`, so a device with a wrong clock can't break the
-- "changed since" sync cursor.
create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- security definer so policies can call these without recursing through RLS.
create function public.is_room_member(p_room_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  return exists (
    select 1 from public.room_members
    where room_id = p_room_id and user_id = auth.uid()
  );
end;
$$;

create function public.is_room_active(p_room_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  return exists (
    select 1 from public.rooms
    where id = p_room_id and status = 'active'
  );
end;
$$;

-- Social: whose workouts the caller may see — their own, plus anyone they
-- follow who shares workouts. Used by the sessions / kudos / comments policies.
create function public.can_view_workouts(p_user_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  return p_user_id = auth.uid() or exists (
    select 1
    from public.follows f
    join public.profiles p on p.id = f.followee_id
    where f.follower_id = auth.uid() and f.followee_id = p_user_id and p.share_workouts
  );
end;
$$;

create function public.can_view_session(p_session_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_owner uuid;
begin
  select user_id into v_owner
  from public.sessions
  where id = p_session_id and deleted_at is null;
  return v_owner is not null and public.can_view_workouts(v_owner);
end;
$$;

-- ===== 01_profiles.sql =====

-- profiles — one per account, created by a trigger on sign-up.

create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 24),
  share_workouts boolean not null default true,  -- followers see this account's workouts in their feed
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger profiles_updated_at
  before insert or update on public.profiles
  for each row execute function public.set_updated_at();

-- Creates the profile from the `display_name` sent with sign-up.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(
      coalesce(
        nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
        nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
        'Athlete'
      ),
      24
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- RLS: any account can find and follow any other, so names are readable by
-- everyone logged in; edit only your own name and sharing choice.
alter table public.profiles enable row level security;
revoke all on public.profiles from anon;

create policy "profiles: read all" on public.profiles
  for select to authenticated
  using (true);

create policy "profiles: update self" on public.profiles
  for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

revoke insert, update, delete on public.profiles from authenticated;
grant update (display_name, share_workouts) on public.profiles to authenticated;

-- ===== 02_routines.sql =====

-- routines — synced copy of the local library (StoredRoutine).

create table public.routines (
  id         uuid primary key,                         -- StoredRoutine.id, generated on the device
  user_id    uuid not null references public.profiles (id) on delete cascade,
  filename   text not null,
  raw_text   text not null check (char_length(raw_text) <= 100000),
  position   integer not null default 0,              -- display order (0 = top)
  created_at timestamptz not null default now(),       -- StoredRoutine.addedAt
  updated_at timestamptz not null default now(),
  deleted_at timestamptz                               -- tombstone so other devices see the delete
);

create index routines_user_updated on public.routines (user_id, updated_at);

create trigger routines_updated_at
  before insert or update on public.routines
  for each row execute function public.set_updated_at();

-- RLS: strictly your own rows.
alter table public.routines enable row level security;
revoke all on public.routines from anon;

create policy "routines: own rows" on public.routines
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- ===== 03_rooms.sql =====

-- rooms — one per group workout.

create table public.rooms (
  id           uuid primary key default gen_random_uuid(),
  code         text not null check (code ~ '^[A-HJKMNP-Z2-9]{6}$'),  -- no 0 O 1 I L
  host_id      uuid references public.profiles (id) on delete set null,
  routine_name text not null,
  routine_wtt  text not null check (char_length(routine_wtt) <= 100000),
  unit         text,
  status       text not null default 'lobby' check (status in ('lobby', 'active', 'finished')),
  created_at   timestamptz not null default now(),
  started_at   timestamptz,
  finished_at  timestamptz
);

-- A code only has to be unique among rooms people can still join.
create unique index rooms_open_code on public.rooms (code) where status <> 'finished';

-- Keeps status moving forward only and stamps started_at / finished_at.
create function public.room_status_transition()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = old.status then
    return new;
  end if;
  if (old.status = 'lobby' and new.status in ('active', 'finished'))
     or (old.status = 'active' and new.status = 'finished') then
    if new.status = 'active' then
      new.started_at := coalesce(new.started_at, now());
    end if;
    if new.status = 'finished' then
      new.finished_at := coalesce(new.finished_at, now());
    end if;
    return new;
  end if;
  raise exception 'invalid room status change: % -> %', old.status, new.status;
end;
$$;

create trigger rooms_status_transition
  before update of status on public.rooms
  for each row execute function public.room_status_transition();

-- RPC: creates a room with a fresh code and the caller as host (and first member).
create function public.create_room(p_routine_wtt text, p_routine_name text, p_unit text default null)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid      uuid := auth.uid();
  v_alphabet constant text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  v_code     text;
  v_room     public.rooms;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  for attempt in 1..10 loop
    v_code := '';
    for i in 1..6 loop
      v_code := v_code || substr(v_alphabet, 1 + floor(random() * length(v_alphabet))::int, 1);
    end loop;

    begin
      insert into public.rooms (code, host_id, routine_name, routine_wtt, unit)
      values (v_code, v_uid, left(p_routine_name, 120), p_routine_wtt, p_unit)
      returning * into v_room;
      exit;
    exception when unique_violation then
      v_room := null;  -- code clash with an open room: try another
    end;
  end loop;

  if v_room.id is null then
    raise exception 'room_code_exhausted';
  end if;

  insert into public.room_members (room_id, user_id) values (v_room.id, v_uid);
  return v_room;
end;
$$;

revoke execute on function public.create_room(text, text, text) from public, anon;
grant execute on function public.create_room(text, text, text) to authenticated;

-- RLS: members read; only the host moves the status. Rows are created by create_room().
alter table public.rooms enable row level security;
revoke all on public.rooms from anon;

create policy "rooms: members read" on public.rooms
  for select to authenticated
  using (public.is_room_member(id));

create policy "rooms: host updates" on public.rooms
  for update to authenticated
  using (host_id = (select auth.uid()))
  with check (host_id = (select auth.uid()));

revoke insert, update, delete on public.rooms from authenticated;
grant update (status) on public.rooms to authenticated;

alter publication supabase_realtime add table public.rooms;

-- ===== 04_room_members.sql =====

-- room_members — who is in each room.

create table public.room_members (
  room_id     uuid not null references public.rooms (id) on delete cascade,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  joined_at   timestamptz not null default now(),
  finished_at timestamptz,
  primary key (room_id, user_id)
);

create index room_members_user on public.room_members (user_id);

-- Closes the room once every member has finished their workout.
create function public.finish_room_when_done()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.finished_at is not null and not exists (
    select 1 from public.room_members
    where room_id = new.room_id and finished_at is null
  ) then
    update public.rooms set status = 'finished'
    where id = new.room_id and status = 'active';
  end if;
  return new;
end;
$$;

create trigger room_members_finish_room
  after update of finished_at on public.room_members
  for each row execute function public.finish_room_when_done();

-- RPC: joins an open room by its code (joining twice is a no-op; max 8 people).
create function public.join_room(p_code text)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid  uuid := auth.uid();
  v_room public.rooms;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  select * into v_room
  from public.rooms
  where code = upper(regexp_replace(p_code, '\s', '', 'g')) and status <> 'finished'
  for update;

  if v_room.id is null then
    raise exception 'room_not_found';
  end if;

  if exists (select 1 from public.room_members where room_id = v_room.id and user_id = v_uid) then
    return v_room;
  end if;

  if (select count(*) from public.room_members where room_id = v_room.id) >= 8 then
    raise exception 'room_full';
  end if;

  insert into public.room_members (room_id, user_id) values (v_room.id, v_uid);
  return v_room;
end;
$$;

revoke execute on function public.join_room(text) from public, anon;
grant execute on function public.join_room(text) to authenticated;

-- RLS: members see each other; you can mark yourself finished or leave.
-- Rows are created by create_room() / join_room().
alter table public.room_members enable row level security;
revoke all on public.room_members from anon;

create policy "room_members: members read" on public.room_members
  for select to authenticated
  using (public.is_room_member(room_id));

create policy "room_members: update self" on public.room_members
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "room_members: leave" on public.room_members
  for delete to authenticated
  using (user_id = (select auth.uid()));

revoke insert, update on public.room_members from authenticated;
grant update (finished_at) on public.room_members to authenticated;

alter publication supabase_realtime add table public.room_members;

-- ===== 05_sessions.sql =====

-- sessions — synced copy of the local session log (StoredSession).

create table public.sessions (
  id         uuid primary key,                         -- StoredSession.id, generated on the device
  user_id    uuid not null references public.profiles (id) on delete cascade,
  routine_id uuid,                                     -- no FK: a session may sync before its routine
  room_id    uuid references public.rooms (id) on delete set null,
  raw_text   text not null check (char_length(raw_text) <= 200000),
  created_at timestamptz not null default now(),       -- StoredSession.addedAt
  updated_at timestamptz not null default now(),
  deleted_at timestamptz                               -- tombstone so other devices see the delete
);

create index sessions_user_updated on public.sessions (user_id, updated_at);

create trigger sessions_updated_at
  before insert or update on public.sessions
  for each row execute function public.set_updated_at();

-- RLS: you own your rows; followers can read the live (non-deleted) ones when
-- you share workouts. The sync pull filters on user_id so those never mix in.
alter table public.sessions enable row level security;
revoke all on public.sessions from anon;

create policy "sessions: own rows" on public.sessions
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "sessions: followers read" on public.sessions
  for select to authenticated
  using (deleted_at is null and public.can_view_workouts(user_id));

create index sessions_user_created on public.sessions (user_id, created_at desc) where deleted_at is null;

-- ===== 06_set_logs.sql =====

-- set_logs — live, completed sets inside a room.

create table public.set_logs (
  id            uuid primary key,                      -- SessionSetDraft.id, so re-sends are idempotent
  room_id       uuid not null,
  user_id       uuid not null,
  exercise_name text not null,
  set_type      text not null check (set_type in ('number', 'W', 'D')),
  weight        numeric(7, 2) not null default 0,
  reps          integer not null default 0 check (reps >= 0),  -- seconds for timed exercises
  completed_at  timestamptz not null default now(),
  foreign key (room_id, user_id) references public.room_members (room_id, user_id) on delete cascade
);

create index set_logs_room on public.set_logs (room_id);

-- RLS: members read everything in the room; you write only your own sets, only while active.
alter table public.set_logs enable row level security;
revoke all on public.set_logs from anon;

create policy "set_logs: members read" on public.set_logs
  for select to authenticated
  using (public.is_room_member(room_id));

create policy "set_logs: insert own while active" on public.set_logs
  for insert to authenticated
  with check (user_id = (select auth.uid()) and public.is_room_active(room_id));

create policy "set_logs: update own while active" on public.set_logs
  for update to authenticated
  using (user_id = (select auth.uid()) and public.is_room_active(room_id))
  with check (user_id = (select auth.uid()) and public.is_room_active(room_id));

create policy "set_logs: delete own while active" on public.set_logs
  for delete to authenticated
  using (user_id = (select auth.uid()) and public.is_room_active(room_id));

alter publication supabase_realtime add table public.set_logs;

-- ===== 07_follows.sql =====

-- follows — one-way, public follows (like Strava / Hevy): following someone
-- puts their shared workouts in your feed. No requests to approve; people who
-- want privacy turn off `profiles.share_workouts` instead.

create table public.follows (
  follower_id uuid not null references public.profiles (id) on delete cascade,
  followee_id uuid not null references public.profiles (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);

create index follows_followee on public.follows (followee_id);

-- RLS: the follow graph is public to accounts; you only add or drop your own follows.
alter table public.follows enable row level security;
revoke all on public.follows from anon;

create policy "follows: read all" on public.follows
  for select to authenticated
  using (true);

create policy "follows: follow as self" on public.follows
  for insert to authenticated
  with check (follower_id = (select auth.uid()));

create policy "follows: unfollow as self" on public.follows
  for delete to authenticated
  using (follower_id = (select auth.uid()));

revoke update on public.follows from authenticated;

-- ===== 08_session_kudos.sql =====

-- session_kudos — a one-tap "nice work" on a workout in the feed.

create table public.session_kudos (
  session_id uuid not null references public.sessions (id) on delete cascade,
  user_id    uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (session_id, user_id)
);

-- RLS: anyone who can see the workout sees its kudos and can give one (as themselves).
alter table public.session_kudos enable row level security;
revoke all on public.session_kudos from anon;

create policy "session_kudos: read visible" on public.session_kudos
  for select to authenticated
  using (public.can_view_session(session_id));

create policy "session_kudos: give as self" on public.session_kudos
  for insert to authenticated
  with check (user_id = (select auth.uid()) and public.can_view_session(session_id));

create policy "session_kudos: take back own" on public.session_kudos
  for delete to authenticated
  using (user_id = (select auth.uid()));

revoke update on public.session_kudos from authenticated;

-- ===== 09_session_comments.sql =====

-- session_comments — short comments under a workout in the feed.

create table public.session_comments (
  id         uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions (id) on delete cascade,
  user_id    uuid not null references public.profiles (id) on delete cascade,
  body       text not null check (char_length(trim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index session_comments_session on public.session_comments (session_id, created_at);

-- RLS: anyone who can see the workout reads and writes comments (as themselves);
-- authors delete their own, and the workout's owner can delete any on it.
alter table public.session_comments enable row level security;
revoke all on public.session_comments from anon;

create policy "session_comments: read visible" on public.session_comments
  for select to authenticated
  using (public.can_view_session(session_id));

create policy "session_comments: write as self" on public.session_comments
  for insert to authenticated
  with check (user_id = (select auth.uid()) and public.can_view_session(session_id));

create policy "session_comments: delete own or on own workout" on public.session_comments
  for delete to authenticated
  using (
    user_id = (select auth.uid())
    or exists (
      select 1 from public.sessions s
      where s.id = session_id and s.user_id = (select auth.uid())
    )
  );

revoke update on public.session_comments from authenticated;

-- ===== 10_social.sql =====

-- Social read functions for the feed, profiles and people search.
--
-- All `security invoker` (the default for `language sql`): they only shape and
-- count rows, and the table policies above still decide what the caller sees.

-- Feed page, newest first, paged by the (created_at, id) of the last row seen.
-- No p_user_id / p_session_id: you and everyone you follow. p_user_id: one
-- person's workouts. p_session_id: a single workout.
create function public.social_feed(
  p_user_id    uuid default null,
  p_before     timestamptz default null,
  p_before_id  uuid default null,
  p_limit      integer default 20,
  p_session_id uuid default null
)
returns table (
  session_id    uuid,
  user_id       uuid,
  display_name  text,
  raw_text      text,
  room_id       uuid,
  created_at    timestamptz,
  kudos_count   integer,
  comment_count integer,
  gave_kudos    boolean
)
language sql
stable
set search_path = ''
as $$
  select
    s.id,
    s.user_id,
    p.display_name,
    s.raw_text,
    s.room_id,
    s.created_at,
    (select count(*)::integer from public.session_kudos k where k.session_id = s.id),
    (select count(*)::integer from public.session_comments c where c.session_id = s.id),
    exists (select 1 from public.session_kudos k where k.session_id = s.id and k.user_id = auth.uid())
  from public.sessions s
  join public.profiles p on p.id = s.user_id
  where s.deleted_at is null
    and case
      when p_session_id is not null then s.id = p_session_id
      when p_user_id is not null then s.user_id = p_user_id
      else s.user_id = auth.uid()
        or s.user_id in (select f.followee_id from public.follows f where f.follower_id = auth.uid())
    end
    and (
      p_before is null
      or s.created_at < p_before
      or (s.created_at = p_before and p_before_id is not null and s.id < p_before_id)
    )
  order by s.created_at desc, s.id desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
$$;

-- One profile with its follow counts and how it relates to the caller.
-- workouts_count only counts what the caller is allowed to see.
create function public.social_profile(p_user_id uuid)
returns table (
  id              uuid,
  display_name    text,
  share_workouts  boolean,
  created_at      timestamptz,
  followers_count integer,
  following_count integer,
  workouts_count  integer,
  is_following    boolean,
  follows_me      boolean
)
language sql
stable
set search_path = ''
as $$
  select
    p.id,
    p.display_name,
    p.share_workouts,
    p.created_at,
    (select count(*)::integer from public.follows f where f.followee_id = p.id),
    (select count(*)::integer from public.follows f where f.follower_id = p.id),
    (select count(*)::integer from public.sessions s where s.user_id = p.id and s.deleted_at is null),
    exists (select 1 from public.follows f where f.follower_id = auth.uid() and f.followee_id = p.id),
    exists (select 1 from public.follows f where f.follower_id = p.id and f.followee_id = auth.uid())
  from public.profiles p
  where p.id = p_user_id;
$$;

-- People whose name contains the query (prefix matches first), not including you.
create function public.search_profiles(p_query text)
returns table (
  id           uuid,
  display_name text,
  is_following boolean,
  follows_me   boolean
)
language sql
stable
set search_path = ''
as $$
  with q as (
    -- Escape LIKE wildcards so "50%" or "a_b" match literally.
    select replace(replace(replace(trim(p_query), '\', '\\'), '%', '\%'), '_', '\_') as term
  )
  select
    p.id,
    p.display_name,
    exists (select 1 from public.follows f where f.follower_id = auth.uid() and f.followee_id = p.id),
    exists (select 1 from public.follows f where f.follower_id = p.id and f.followee_id = auth.uid())
  from public.profiles p, q
  where p.id <> auth.uid()
    and char_length(q.term) >= 2
    and p.display_name ilike '%' || q.term || '%'
  order by (p.display_name ilike q.term || '%') desc, lower(p.display_name)
  limit 25;
$$;

-- People you might want to follow and why: you trained together, they follow
-- you, a friend follows them, or — so a new account never sees an empty list —
-- they're new here. Anyone you already follow is left out.
create function public.suggested_profiles(p_limit integer default 12)
returns table (
  id           uuid,
  display_name text,
  reason       text,
  follows_me   boolean
)
language sql
stable
set search_path = ''
as $$
  with candidates as (
    select them.user_id as id, 0 as rank
    from public.room_members me
    join public.room_members them on them.room_id = me.room_id
    where me.user_id = auth.uid()
    union all
    select f.follower_id, 1
    from public.follows f
    where f.followee_id = auth.uid()
    union all
    select f2.followee_id, 2
    from public.follows f1
    join public.follows f2 on f2.follower_id = f1.followee_id
    where f1.follower_id = auth.uid()
    union all
    select newest.id, 3
    from (select id from public.profiles order by created_at desc limit 20) newest
  ),
  ranked as (
    select c.id, min(c.rank) as rank, count(*) as weight
    from candidates c
    where c.id <> auth.uid()
      and not exists (select 1 from public.follows f where f.follower_id = auth.uid() and f.followee_id = c.id)
    group by c.id
  )
  select
    p.id,
    p.display_name,
    case r.rank
      when 0 then 'trained_together'
      when 1 then 'follows_you'
      when 2 then 'friend_of_friend'
      else 'new'
    end,
    exists (select 1 from public.follows f where f.follower_id = p.id and f.followee_id = auth.uid())
  from ranked r
  join public.profiles p on p.id = r.id
  order by r.rank, r.weight desc, p.created_at desc
  limit least(greatest(coalesce(p_limit, 12), 1), 30);
$$;

-- Someone's followers or the people they follow, newest first.
create function public.follow_list(p_user_id uuid, p_kind text)
returns table (
  id           uuid,
  display_name text,
  is_following boolean,
  follows_me   boolean
)
language sql
stable
set search_path = ''
as $$
  select
    p.id,
    p.display_name,
    exists (select 1 from public.follows f where f.follower_id = auth.uid() and f.followee_id = p.id),
    exists (select 1 from public.follows f where f.follower_id = p.id and f.followee_id = auth.uid())
  from public.follows link
  join public.profiles p
    on p.id = case when p_kind = 'followers' then link.follower_id else link.followee_id end
  where case when p_kind = 'followers' then link.followee_id else link.follower_id end = p_user_id
  order by link.created_at desc
  limit 200;
$$;

-- A workout's comments, oldest first, with each author's name.
create function public.post_comments(p_session_id uuid)
returns table (
  id           uuid,
  user_id      uuid,
  display_name text,
  body         text,
  created_at   timestamptz
)
language sql
stable
set search_path = ''
as $$
  select c.id, c.user_id, p.display_name, c.body, c.created_at
  from public.session_comments c
  join public.profiles p on p.id = c.user_id
  where c.session_id = p_session_id
  order by c.created_at
  limit 500;
$$;

-- Who gave a workout kudos, newest first.
create function public.post_kudos(p_session_id uuid)
returns table (
  user_id      uuid,
  display_name text
)
language sql
stable
set search_path = ''
as $$
  select k.user_id, p.display_name
  from public.session_kudos k
  join public.profiles p on p.id = k.user_id
  where k.session_id = p_session_id
  order by k.created_at desc
  limit 500;
$$;

revoke execute on function public.social_feed(uuid, timestamptz, uuid, integer, uuid) from public, anon;
revoke execute on function public.social_profile(uuid) from public, anon;
revoke execute on function public.search_profiles(text) from public, anon;
revoke execute on function public.suggested_profiles(integer) from public, anon;
revoke execute on function public.follow_list(uuid, text) from public, anon;
revoke execute on function public.post_comments(uuid) from public, anon;
revoke execute on function public.post_kudos(uuid) from public, anon;

grant execute on function public.social_feed(uuid, timestamptz, uuid, integer, uuid) to authenticated;
grant execute on function public.social_profile(uuid) to authenticated;
grant execute on function public.search_profiles(text) to authenticated;
grant execute on function public.suggested_profiles(integer) to authenticated;
grant execute on function public.follow_list(uuid, text) to authenticated;
grant execute on function public.post_comments(uuid) to authenticated;
grant execute on function public.post_kudos(uuid) to authenticated;
