<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { renderSVG } from 'uqr'
import { buildImportUrl } from '@/lib/share'
import BottomSheet from '@/components/ui/BottomSheet.vue'

const props = defineProps<{
  open: boolean
  rawText: string
  name: string
}>()

const emit = defineEmits<{
  'update:open': [value: boolean]
}>()

const router = useRouter()

const importPath = computed(() => router.resolve({ name: 'import' }).href)
const url = computed(() => buildImportUrl(props.rawText, importPath.value))

const qr = computed<{ svg: string } | { error: string }>(() => {
  try {
    return {
      svg: renderSVG(url.value, {
        ecc: 'M',
        border: 2,
        pixelSize: 8,
        whiteColor: '#ffffff',
        blackColor: '#0b0b0b',
      }),
    }
  } catch {
    return { error: 'This routine is too large to fit in a QR code. Use “Copy link”.' }
  }
})

const copied = ref<'link' | 'text' | null>(null)

const canNativeShare = typeof navigator !== 'undefined' && typeof navigator.share === 'function'

async function nativeShare() {
  try {
    await navigator.share({
      title: props.name || 'wtx routine',
      text: `${props.name} — open in wtx`,
      url: url.value,
    })
  } catch {
    /* user dismissed the share sheet, or it's unavailable */
  }
}

async function copy(kind: 'link' | 'text') {
  const value = kind === 'link' ? url.value : props.rawText
  try {
    await navigator.clipboard.writeText(value)
    copied.value = kind
    setTimeout(() => {
      if (copied.value === kind) copied.value = null
    }, 1500)
  } catch {
    /* clipboard blocked — the field below is selectable as a fallback */
  }
}

function close() {
  emit('update:open', false)
}

watch(
  () => props.open,
  (open) => {
    if (!open) copied.value = null
  },
)
</script>

<template>
  <BottomSheet :open="open" title="Share routine" @close="close">
    <div class="qr-card">
      <!-- eslint-disable-next-line vue/no-v-html -- SVG is generated by uqr from our own URL -->
      <div v-if="'svg' in qr" class="qr" v-html="qr.svg" />
      <p v-else class="warn">{{ qr.error }}</p>
    </div>

    <p class="name">{{ name }}</p>
    <p class="hint">Scan the QR to open this routine in wtx, or share the link another way.</p>

    <button v-if="canNativeShare" type="button" class="share-native" @click="nativeShare">
      Share to another app…
    </button>

    <label class="link-row">
      <span class="sr-only">Import link</span>
      <input
        :value="url"
        readonly
        spellcheck="false"
        @focus="($event.target as HTMLInputElement).select()"
      />
    </label>

    <div class="actions">
      <button type="button" class="primary" @click="copy('link')">
        {{ copied === 'link' ? 'Copied' : 'Copy link' }}
      </button>
      <button type="button" class="secondary" @click="copy('text')">
        {{ copied === 'text' ? 'Copied' : 'Copy .wtt text' }}
      </button>
    </div>
  </BottomSheet>
</template>

<style scoped>
.qr-card {
  align-self: center;
  display: grid;
  place-items: center;
  width: 100%;
  max-width: 280px;
  aspect-ratio: 1;
  padding: 16px;
  background: #fff;
  border-radius: var(--radius-lg);
}

.qr {
  width: 100%;
  line-height: 0;
}

.qr :deep(svg) {
  width: 100%;
  height: auto;
  display: block;
}

.warn {
  font-size: 13px;
  color: #b45309;
  text-align: center;
}

.name {
  text-align: center;
  font-size: 15px;
  font-weight: 700;
  color: var(--color-heading);
}

.hint {
  text-align: center;
  font-size: 12px;
  opacity: 0.65;
  margin-top: -6px;
}

.share-native {
  width: 100%;
  border: 1px solid var(--color-border-hover);
  background: var(--color-background-soft);
  color: var(--color-text);
  font-size: 13px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: var(--label-tracking);
  padding: 12px;
  border-radius: var(--radius-md);
  cursor: pointer;
}

.link-row input {
  width: 100%;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 12px;
  padding: 10px 12px;
  border-radius: var(--radius-md);
  border: 1px solid var(--color-border);
  background: var(--color-background-soft);
  color: var(--color-text);
}

.actions {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
}

.actions button {
  border: none;
  border-radius: var(--radius-md);
  padding: 13px;
  font-size: 13px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: var(--label-tracking);
  cursor: pointer;
}

.primary {
  color: #fff;
  background: var(--color-accent);
}

.secondary {
  color: var(--color-text);
  background: var(--color-background-mute);
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
}
</style>
