<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { renderSVG } from 'uqr'
import { buildImportUrl } from '@/lib/share'

const props = defineProps<{
  open: boolean
  rawText: string
  name: string
}>()

const emit = defineEmits<{
  'update:open': [value: boolean]
}>()

const router = useRouter()

const importPath = computed(() => router.resolve({ name: 'import' }).href)
const url = computed(() => buildImportUrl(props.rawText, importPath.value))

const qr = computed<{ svg: string } | { error: string }>(() => {
  try {
    return {
      svg: renderSVG(url.value, {
        ecc: 'M',
        border: 2,
        pixelSize: 8,
        whiteColor: '#ffffff',
        blackColor: '#0b0b0b',
      }),
    }
  } catch {
    return { error: 'This routine is too large to fit in a QR code. Use “Copy link”.' }
  }
})

const copied = ref<'link' | 'text' | null>(null)

async function copy(kind: 'link' | 'text') {
  const value = kind === 'link' ? url.value : props.rawText
  try {
    await navigator.clipboard.writeText(value)
    copied.value = kind
    setTimeout(() => {
      if (copied.value === kind) copied.value = null
    }, 1500)
  } catch {
    /* clipboard blocked — the field below is selectable as a fallback */
  }
}

function close() {
  emit('update:open', false)
}

watch(
  () => props.open,
  (open) => {
    if (!open) copied.value = null
  },
)
</script>

<template>
  <Teleport to="body">
    <Transition name="sheet">
      <div
        v-if="open"
        class="scrim"
        role="dialog"
        aria-modal="true"
        aria-label="Share routine"
        @click.self="close"
        @keydown.esc="close"
      >
        <div class="sheet">
          <div class="sheet__grabber" />
          <header class="sheet__head">
            <h2>Share routine</h2>
            <button type="button" class="icon-btn" aria-label="Close" @click="close">✕</button>
          </header>

          <div class="qr-card">
            <!-- eslint-disable-next-line vue/no-v-html -- SVG is generated by uqr from our own URL -->
            <div v-if="'svg' in qr" class="qr" v-html="qr.svg" />
            <p v-else class="warn">{{ qr.error }}</p>
          </div>

          <p class="name">{{ name }}</p>
          <p class="hint">Scan to open this routine in wtx and add it.</p>

          <label class="link-row">
            <span class="sr-only">Import link</span>
            <input
              :value="url"
              readonly
              spellcheck="false"
              @focus="($event.target as HTMLInputElement).select()"
            />
          </label>

          <div class="actions">
            <button type="button" class="primary" @click="copy('link')">
              {{ copied === 'link' ? 'Copied' : 'Copy link' }}
            </button>
            <button type="button" class="secondary" @click="copy('text')">
              {{ copied === 'text' ? 'Copied' : 'Copy .wtt text' }}
            </button>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.scrim {
  position: fixed;
  inset: 0;
  z-index: 100;
  display: flex;
  align-items: flex-end;
  justify-content: center;
  background: rgba(0, 0, 0, 0.4);
}

.sheet {
  width: 100%;
  max-width: 480px;
  max-height: 90dvh;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 8px 20px calc(20px + env(safe-area-inset-bottom));
  background: var(--color-background);
  border-radius: 20px 20px 0 0;
}

.sheet__grabber {
  align-self: center;
  width: 36px;
  height: 4px;
  border-radius: 2px;
  background: var(--color-border-hover);
  margin: 4px 0;
}

.sheet__head {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.sheet__head h2 {
  font-size: 17px;
  font-weight: 700;
  color: var(--color-heading);
}

.icon-btn {
  border: none;
  background: transparent;
  color: var(--color-text);
  font-size: 15px;
  padding: 6px;
  cursor: pointer;
  opacity: 0.6;
}

.qr-card {
  align-self: center;
  display: grid;
  place-items: center;
  width: 100%;
  max-width: 280px;
  aspect-ratio: 1;
  padding: 16px;
  background: #fff;
  border-radius: 16px;
}

.qr {
  width: 100%;
  line-height: 0;
}

.qr :deep(svg) {
  width: 100%;
  height: auto;
  display: block;
}

.warn {
  font-size: 13px;
  color: #b45309;
  text-align: center;
}

.name {
  text-align: center;
  font-size: 15px;
  font-weight: 700;
  color: var(--color-heading);
}

.hint {
  text-align: center;
  font-size: 12px;
  opacity: 0.65;
  margin-top: -6px;
}

.link-row input {
  width: 100%;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 12px;
  padding: 10px 12px;
  border-radius: 10px;
  border: 1px solid var(--color-border);
  background: var(--color-background-soft);
  color: var(--color-text);
}

.actions {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
}

.actions button {
  border: none;
  border-radius: 12px;
  padding: 13px;
  font-size: 14px;
  font-weight: 700;
  cursor: pointer;
}

.primary {
  color: #fff;
  background: var(--color-accent);
}

.secondary {
  color: var(--color-text);
  background: var(--color-background-mute);
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
}

.sheet-enter-active,
.sheet-leave-active {
  transition: opacity 0.2s ease;
}

.sheet-enter-active .sheet,
.sheet-leave-active .sheet {
  transition: transform 0.25s ease;
}

.sheet-enter-from,
.sheet-leave-to {
  opacity: 0;
}

.sheet-enter-from .sheet,
.sheet-leave-to .sheet {
  transform: translateY(100%);
}
</style>
