<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { renderSVG } from 'uqr'
import BottomSheet from '@/components/ui/BottomSheet.vue'
import { useAuthStore } from '@/stores/auth'
import { isRateLimited } from '@/lib/supabase/limits'

const props = defineProps<{
  code: string
  followUrl: string
}>()

const { t } = useI18n()

const svg = computed(() =>
  renderSVG(props.followUrl, {
    ecc: 'M',
    border: 2,
    pixelSize: 8,
    whiteColor: '#ffffff',
    blackColor: '#0b0b0b',
  }),
)

const copied = ref(false)
const canNativeShare = typeof navigator !== 'undefined' && typeof navigator.share === 'function'

async function copyLink() {
  try {
    await navigator.clipboard.writeText(props.followUrl)
    copied.value = true
    setTimeout(() => (copied.value = false), 1500)
  } catch {
    /* clipboard blocked — the link is on screen anyway */
  }
}

// ----- reset code: old links and QR codes stop working -----
const auth = useAuthStore()
const resetOpen = ref(false)
const resetting = ref(false)
const resetError = ref('')

function openReset() {
  resetError.value = ''
  resetOpen.value = true
}

async function confirmReset() {
  if (resetting.value) return
  resetting.value = true
  resetError.value = ''
  try {
    await auth.rotateInviteCode()
    resetOpen.value = false
  } catch (e) {
    resetError.value = t(isRateLimited(e) ? 'social.follow.resetRateLimited' : 'social.follow.resetFailed')
  } finally {
    resetting.value = false
  }
}

async function share() {
  try {
    await navigator.share({
      text: t('social.follow.shareText'),
      url: props.followUrl,
    })
  } catch {
    /* dismissed */
  }
}
</script>

<template>
  <div class="card">
    <!-- eslint-disable-next-line vue/no-v-html -- SVG is generated by uqr from our own URL -->
    <div class="qr" v-html="svg" />
    <div class="code-block">
      <span class="code-block__label">{{ t('social.follow.yourCode') }}</span>
      <span class="code-block__code">{{ code.slice(0, 4) }} {{ code.slice(4) }}</span>
    </div>
    <p class="hint">{{ t('social.follow.shareHint') }}</p>
    <div class="actions">
      <button type="button" class="secondary" @click="copyLink">
        {{ copied ? t('room.copied') : t('social.follow.copyLink') }}
      </button>
      <button v-if="canNativeShare" type="button" class="secondary" @click="share">
        {{ t('room.shareLink') }}
      </button>
    </div>
    <button type="button" class="reset" @click="openReset">{{ t('social.follow.resetCode') }}</button>

    <BottomSheet :open="resetOpen" :title="t('social.follow.resetTitle')" @close="resetOpen = false">
      <div class="sheet">
        <p class="sheet__hint">{{ t('social.follow.resetHint') }}</p>
        <p v-if="resetError" class="sheet__error" role="status">{{ resetError }}</p>
        <button type="button" class="sheet__danger" :disabled="resetting" @click="confirmReset">
          {{ t('social.follow.resetConfirm') }}
        </button>
        <button type="button" class="sheet__secondary" @click="resetOpen = false">
          {{ t('common.cancel') }}
        </button>
      </div>
    </BottomSheet>
  </div>
</template>

<style scoped>
.card {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  padding: 16px;
  border-radius: var(--radius-lg);
  border: 1px solid var(--color-border);
  background: var(--color-background-soft);
}

.qr {
  width: 100%;
  max-width: 200px;
  padding: 10px;
  background: #fff;
  border-radius: var(--radius-md);
  line-height: 0;
}

.qr :deep(svg) {
  width: 100%;
  height: auto;
  display: block;
}

.code-block {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
}

.code-block__label {
  font-size: var(--label-size);
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: var(--label-tracking);
  opacity: 0.6;
}

.code-block__code {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 26px;
  font-weight: 700;
  letter-spacing: 0.12em;
  color: var(--color-heading);
}

.hint {
  font-size: 12px;
  text-align: center;
  opacity: 0.7;
}

.actions {
  display: flex;
  gap: 8px;
  width: 100%;
}

.secondary {
  flex: 1;
  border: 1px solid var(--color-border-hover);
  border-radius: var(--radius-md);
  padding: 11px;
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: var(--label-tracking);
  color: var(--color-text);
  background: var(--color-background-mute);
  cursor: pointer;
}

.reset {
  border: none;
  background: none;
  padding: 4px 8px;
  font-size: 12px;
  font-weight: 600;
  color: var(--color-text);
  opacity: 0.6;
  text-decoration: underline;
  cursor: pointer;
}

.sheet {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 4px 0 12px;
}

.sheet__hint {
  font-size: 13px;
  opacity: 0.75;
}

.sheet__error {
  font-size: 13px;
  color: #e11d48;
}

.sheet__danger,
.sheet__secondary {
  min-height: 48px;
  border-radius: var(--radius-md);
  font-size: 13px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: var(--label-tracking);
  cursor: pointer;
}

.sheet__danger {
  border: none;
  background: #e11d48;
  color: #fff;
}

.sheet__danger:disabled {
  opacity: 0.5;
  cursor: default;
}

.sheet__secondary {
  border: 1px solid var(--color-border-hover);
  background: transparent;
  color: var(--color-heading);
}
</style>
