<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { renderSVG } from 'uqr'

const props = defineProps<{
  code: string
  joinUrl: string
  routineName: string
}>()

const { t } = useI18n()

const svg = computed(() =>
  renderSVG(props.joinUrl, {
    ecc: 'M',
    border: 2,
    pixelSize: 8,
    whiteColor: '#ffffff',
    blackColor: '#0b0b0b',
  }),
)

const copied = ref(false)
const canNativeShare = typeof navigator !== 'undefined' && typeof navigator.share === 'function'

async function copyCode() {
  try {
    await navigator.clipboard.writeText(props.code)
    copied.value = true
    setTimeout(() => (copied.value = false), 1500)
  } catch {
    /* clipboard blocked — the code is on screen anyway */
  }
}

async function share() {
  try {
    await navigator.share({
      title: props.routineName,
      text: t('room.shareText', { name: props.routineName, code: props.code }),
      url: props.joinUrl,
    })
  } catch {
    /* dismissed */
  }
}
</script>

<template>
  <div class="card">
    <!-- eslint-disable-next-line vue/no-v-html -- SVG is generated by uqr from our own URL -->
    <div class="qr" v-html="svg" />
    <div class="code-block">
      <span class="code-block__label">{{ t('room.code') }}</span>
      <span class="code-block__code">{{ code.slice(0, 3) }} {{ code.slice(3) }}</span>
    </div>
    <p class="hint">{{ t('room.shareHint') }}</p>
    <div class="actions">
      <button type="button" class="secondary" @click="copyCode">
        {{ copied ? t('room.copied') : t('room.copyCode') }}
      </button>
      <button v-if="canNativeShare" type="button" class="secondary" @click="share">
        {{ t('room.shareLink') }}
      </button>
    </div>
  </div>
</template>

<style scoped>
.card {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  padding: 16px;
  border-radius: var(--radius-lg);
  border: 1px solid var(--color-border);
  background: var(--color-background-soft);
}

.qr {
  width: 100%;
  max-width: 200px;
  padding: 10px;
  background: #fff;
  border-radius: var(--radius-md);
  line-height: 0;
}

.qr :deep(svg) {
  width: 100%;
  height: auto;
  display: block;
}

.code-block {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
}

.code-block__label {
  font-size: var(--label-size);
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: var(--label-tracking);
  opacity: 0.6;
}

.code-block__code {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 30px;
  font-weight: 700;
  letter-spacing: 0.12em;
  color: var(--color-heading);
}

.hint {
  font-size: 12px;
  text-align: center;
  opacity: 0.7;
}

.actions {
  display: flex;
  gap: 8px;
  width: 100%;
}

.secondary {
  flex: 1;
  border: 1px solid var(--color-border-hover);
  border-radius: var(--radius-md);
  padding: 11px;
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: var(--label-tracking);
  color: var(--color-text);
  background: var(--color-background-mute);
  cursor: pointer;
}
</style>
