<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { renderSVG } from 'uqr'
import { Copy, Share2 } from '@lucide/vue'
import BottomSheet from '@/components/ui/BottomSheet.vue'
import { useAuthStore } from '@/stores/auth'
import { useUiStore } from '@/stores/ui'
import { buildFollowUrl } from '@/lib/followCode'
import { canShare, shareLink } from '@/services/nativeShare'

/**
 * The one place a profile is shared from. Every "share" entry point (the
 * profile's header icon and button, and the Friends tab) opens this sheet:
 * the QR and code for someone standing next to you, and from here the system
 * share sheet or a copied link for everyone else.
 */
const { t } = useI18n()
const router = useRouter()
const auth = useAuthStore()
const ui = useUiStore()

const code = computed(() => auth.inviteCode ?? '')
const followUrl = computed(() =>
  code.value ? buildFollowUrl(code.value, router.resolve({ name: 'follow' }).href) : '',
)

const svg = computed(() =>
  followUrl.value
    ? renderSVG(followUrl.value, {
        ecc: 'M',
        border: 2,
        pixelSize: 8,
        whiteColor: '#ffffff',
        blackColor: '#0b0b0b',
      })
    : '',
)

const canNativeShare = canShare()
const copied = ref(false)

async function copyLink() {
  try {
    await navigator.clipboard.writeText(followUrl.value)
    copied.value = true
    setTimeout(() => (copied.value = false), 1500)
  } catch {
    /* clipboard blocked — the code is on screen anyway */
  }
}

async function shareExternally() {
  try {
    await shareLink({ text: t('social.follow.shareText'), url: followUrl.value })
  } catch {
    /* dismissed */
  }
}

/** The other half of connecting: following a friend with their code. */
function enterCode() {
  ui.close()
  router.push({ name: 'follow' })
}
</script>

<template>
  <BottomSheet
    :open="ui.shareProfileSheetOpen"
    :title="t('social.profile.shareProfile')"
    @close="ui.close()"
  >
    <div v-if="code" class="share">
      <!-- eslint-disable-next-line vue/no-v-html -- SVG is generated by uqr from our own URL -->
      <div class="share__qr" v-html="svg" />
      <p class="share__label">{{ t('social.follow.yourCode') }}</p>
      <p class="share__code">{{ code.slice(0, 4) }} {{ code.slice(4) }}</p>
      <p class="share__hint">{{ t('social.follow.shareHint') }}</p>

      <div class="share__actions">
        <button v-if="canNativeShare" type="button" class="share__btn" @click="shareExternally">
          <Share2 :size="18" :stroke-width="2.25" />
          {{ t('share.shareNative') }}
        </button>
        <button type="button" class="share__btn" @click="copyLink">
          <Copy :size="18" :stroke-width="2.25" />
          {{ copied ? t('room.copied') : t('social.follow.copyLink') }}
        </button>
      </div>

      <button type="button" class="share__link" @click="enterCode">
        {{ t('social.follow.enterCode') }}
      </button>
    </div>
  </BottomSheet>
</template>

<style scoped>
.share {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 4px 0 8px;
  text-align: center;
}

.share__qr {
  width: min(64vw, 240px);
  padding: 10px;
  border-radius: 16px;
  background: #ffffff;
}

.share__qr :deep(svg) {
  display: block;
  width: 100%;
  height: auto;
}

.share__label {
  margin-top: 16px;
  font-size: 13px;
  font-weight: 600;
}

.share__code {
  font-size: 28px;
  font-weight: 800;
  letter-spacing: 0.08em;
  color: var(--color-heading);
  font-variant-numeric: tabular-nums;
  user-select: text;
  -webkit-user-select: text;
}

.share__hint {
  max-width: 300px;
  margin-top: 6px;
  font-size: 13px;
  line-height: 1.45;
}

.share__actions {
  display: flex;
  flex-direction: column;
  gap: 10px;
  width: 100%;
  margin-top: 18px;
}

.share__btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  min-height: 52px;
  padding: 8px 14px;
  border: 1px solid var(--color-border-hover);
  border-radius: 14px;
  font: inherit;
  font-size: 14px;
  font-weight: 700;
  color: var(--color-heading);
  background: transparent;
  cursor: pointer;
}

.share__btn:active {
  background: var(--color-background-mute);
}

.share__link {
  height: 44px;
  margin-top: 6px;
  border: none;
  font: inherit;
  font-size: 13px;
  font-weight: 600;
  color: var(--color-text);
  background: transparent;
  text-decoration: underline;
  text-underline-offset: 3px;
  cursor: pointer;
}
</style>
