-- GENERATED by scripts/build-db-migration.mjs — do not edit by hand.
-- Source of truth: supabase/tables/*.sql (applied in file-name order).

-- ===== 00_helpers.sql =====

-- Shared helpers used by the table files that follow.
--
-- The room helpers are plpgsql on purpose: unlike `language sql`, their bodies
-- aren't resolved until they run, so tables created earlier (profiles, rooms)
-- can use them in policies before `room_members` exists.

-- Server-owned `updated_at`, so a device with a wrong clock can't break the
-- "changed since" sync cursor.
create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- security definer so policies can call these without recursing through RLS.
create function public.is_room_member(p_room_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  return exists (
    select 1 from public.room_members
    where room_id = p_room_id and user_id = auth.uid()
  );
end;
$$;

create function public.is_room_active(p_room_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  return exists (
    select 1 from public.rooms
    where id = p_room_id and status = 'active'
  );
end;
$$;

create function public.shares_room_with(p_user_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  return exists (
    select 1
    from public.room_members me
    join public.room_members them on them.room_id = me.room_id
    where me.user_id = auth.uid() and them.user_id = p_user_id
  );
end;
$$;

-- ===== 01_profiles.sql =====

-- profiles — one per account, created by a trigger on sign-up.

create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 24),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger profiles_updated_at
  before insert or update on public.profiles
  for each row execute function public.set_updated_at();

-- Creates the profile from the `display_name` sent with sign-up.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(
      coalesce(
        nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
        nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
        'Athlete'
      ),
      24
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- RLS: see yourself and people you share a room with; edit only your own name.
alter table public.profiles enable row level security;
revoke all on public.profiles from anon;

create policy "profiles: read self and roommates" on public.profiles
  for select to authenticated
  using (id = (select auth.uid()) or public.shares_room_with(id));

create policy "profiles: update self" on public.profiles
  for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

revoke insert, update, delete on public.profiles from authenticated;
grant update (display_name) on public.profiles to authenticated;

-- ===== 02_routines.sql =====

-- routines — synced copy of the local library (StoredRoutine).

create table public.routines (
  id         uuid primary key,                         -- StoredRoutine.id, generated on the device
  user_id    uuid not null references public.profiles (id) on delete cascade,
  filename   text not null,
  raw_text   text not null check (char_length(raw_text) <= 100000),
  position   integer not null default 0,              -- display order (0 = top)
  created_at timestamptz not null default now(),       -- StoredRoutine.addedAt
  updated_at timestamptz not null default now(),
  deleted_at timestamptz                               -- tombstone so other devices see the delete
);

create index routines_user_updated on public.routines (user_id, updated_at);

create trigger routines_updated_at
  before insert or update on public.routines
  for each row execute function public.set_updated_at();

-- RLS: strictly your own rows.
alter table public.routines enable row level security;
revoke all on public.routines from anon;

create policy "routines: own rows" on public.routines
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- ===== 03_rooms.sql =====

-- rooms — one per group workout.

create table public.rooms (
  id           uuid primary key default gen_random_uuid(),
  code         text not null check (code ~ '^[A-HJKMNP-Z2-9]{6}$'),  -- no 0 O 1 I L
  host_id      uuid references public.profiles (id) on delete set null,
  routine_name text not null,
  routine_wtt  text not null check (char_length(routine_wtt) <= 100000),
  unit         text,
  status       text not null default 'lobby' check (status in ('lobby', 'active', 'finished')),
  created_at   timestamptz not null default now(),
  started_at   timestamptz,
  finished_at  timestamptz
);

-- A code only has to be unique among rooms people can still join.
create unique index rooms_open_code on public.rooms (code) where status <> 'finished';

-- Keeps status moving forward only and stamps started_at / finished_at.
create function public.room_status_transition()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = old.status then
    return new;
  end if;
  if (old.status = 'lobby' and new.status in ('active', 'finished'))
     or (old.status = 'active' and new.status = 'finished') then
    if new.status = 'active' then
      new.started_at := coalesce(new.started_at, now());
    end if;
    if new.status = 'finished' then
      new.finished_at := coalesce(new.finished_at, now());
    end if;
    return new;
  end if;
  raise exception 'invalid room status change: % -> %', old.status, new.status;
end;
$$;

create trigger rooms_status_transition
  before update of status on public.rooms
  for each row execute function public.room_status_transition();

-- RPC: creates a room with a fresh code and the caller as host (and first member).
create function public.create_room(p_routine_wtt text, p_routine_name text, p_unit text default null)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid      uuid := auth.uid();
  v_alphabet constant text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  v_code     text;
  v_room     public.rooms;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  for attempt in 1..10 loop
    v_code := '';
    for i in 1..6 loop
      v_code := v_code || substr(v_alphabet, 1 + floor(random() * length(v_alphabet))::int, 1);
    end loop;

    begin
      insert into public.rooms (code, host_id, routine_name, routine_wtt, unit)
      values (v_code, v_uid, left(p_routine_name, 120), p_routine_wtt, p_unit)
      returning * into v_room;
      exit;
    exception when unique_violation then
      v_room := null;  -- code clash with an open room: try another
    end;
  end loop;

  if v_room.id is null then
    raise exception 'room_code_exhausted';
  end if;

  insert into public.room_members (room_id, user_id) values (v_room.id, v_uid);
  return v_room;
end;
$$;

revoke execute on function public.create_room(text, text, text) from public, anon;
grant execute on function public.create_room(text, text, text) to authenticated;

-- RLS: members read; only the host moves the status. Rows are created by create_room().
alter table public.rooms enable row level security;
revoke all on public.rooms from anon;

create policy "rooms: members read" on public.rooms
  for select to authenticated
  using (public.is_room_member(id));

create policy "rooms: host updates" on public.rooms
  for update to authenticated
  using (host_id = (select auth.uid()))
  with check (host_id = (select auth.uid()));

revoke insert, update, delete on public.rooms from authenticated;
grant update (status) on public.rooms to authenticated;

alter publication supabase_realtime add table public.rooms;

-- ===== 04_room_members.sql =====

-- room_members — who is in each room.

create table public.room_members (
  room_id     uuid not null references public.rooms (id) on delete cascade,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  joined_at   timestamptz not null default now(),
  finished_at timestamptz,
  primary key (room_id, user_id)
);

create index room_members_user on public.room_members (user_id);

-- Closes the room once every member has finished their workout.
create function public.finish_room_when_done()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.finished_at is not null and not exists (
    select 1 from public.room_members
    where room_id = new.room_id and finished_at is null
  ) then
    update public.rooms set status = 'finished'
    where id = new.room_id and status = 'active';
  end if;
  return new;
end;
$$;

create trigger room_members_finish_room
  after update of finished_at on public.room_members
  for each row execute function public.finish_room_when_done();

-- RPC: joins an open room by its code (joining twice is a no-op; max 8 people).
create function public.join_room(p_code text)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid  uuid := auth.uid();
  v_room public.rooms;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  select * into v_room
  from public.rooms
  where code = upper(regexp_replace(p_code, '\s', '', 'g')) and status <> 'finished'
  for update;

  if v_room.id is null then
    raise exception 'room_not_found';
  end if;

  if exists (select 1 from public.room_members where room_id = v_room.id and user_id = v_uid) then
    return v_room;
  end if;

  if (select count(*) from public.room_members where room_id = v_room.id) >= 8 then
    raise exception 'room_full';
  end if;

  insert into public.room_members (room_id, user_id) values (v_room.id, v_uid);
  return v_room;
end;
$$;

revoke execute on function public.join_room(text) from public, anon;
grant execute on function public.join_room(text) to authenticated;

-- RLS: members see each other; you can mark yourself finished or leave.
-- Rows are created by create_room() / join_room().
alter table public.room_members enable row level security;
revoke all on public.room_members from anon;

create policy "room_members: members read" on public.room_members
  for select to authenticated
  using (public.is_room_member(room_id));

create policy "room_members: update self" on public.room_members
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "room_members: leave" on public.room_members
  for delete to authenticated
  using (user_id = (select auth.uid()));

revoke insert, update on public.room_members from authenticated;
grant update (finished_at) on public.room_members to authenticated;

alter publication supabase_realtime add table public.room_members;

-- ===== 05_sessions.sql =====

-- sessions — synced copy of the local session log (StoredSession).

create table public.sessions (
  id         uuid primary key,                         -- StoredSession.id, generated on the device
  user_id    uuid not null references public.profiles (id) on delete cascade,
  routine_id uuid,                                     -- no FK: a session may sync before its routine
  room_id    uuid references public.rooms (id) on delete set null,
  raw_text   text not null check (char_length(raw_text) <= 200000),
  created_at timestamptz not null default now(),       -- StoredSession.addedAt
  updated_at timestamptz not null default now(),
  deleted_at timestamptz                               -- tombstone so other devices see the delete
);

create index sessions_user_updated on public.sessions (user_id, updated_at);

create trigger sessions_updated_at
  before insert or update on public.sessions
  for each row execute function public.set_updated_at();

-- RLS: strictly your own rows.
alter table public.sessions enable row level security;
revoke all on public.sessions from anon;

create policy "sessions: own rows" on public.sessions
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- ===== 06_set_logs.sql =====

-- set_logs — live, completed sets inside a room.

create table public.set_logs (
  id            uuid primary key,                      -- SessionSetDraft.id, so re-sends are idempotent
  room_id       uuid not null,
  user_id       uuid not null,
  exercise_name text not null,
  set_type      text not null check (set_type in ('number', 'W', 'D')),
  weight        numeric(7, 2) not null default 0,
  reps          integer not null default 0 check (reps >= 0),  -- seconds for timed exercises
  completed_at  timestamptz not null default now(),
  foreign key (room_id, user_id) references public.room_members (room_id, user_id) on delete cascade
);

create index set_logs_room on public.set_logs (room_id);

-- RLS: members read everything in the room; you write only your own sets, only while active.
alter table public.set_logs enable row level security;
revoke all on public.set_logs from anon;

create policy "set_logs: members read" on public.set_logs
  for select to authenticated
  using (public.is_room_member(room_id));

create policy "set_logs: insert own while active" on public.set_logs
  for insert to authenticated
  with check (user_id = (select auth.uid()) and public.is_room_active(room_id));

create policy "set_logs: update own while active" on public.set_logs
  for update to authenticated
  using (user_id = (select auth.uid()) and public.is_room_active(room_id))
  with check (user_id = (select auth.uid()) and public.is_room_active(room_id));

create policy "set_logs: delete own while active" on public.set_logs
  for delete to authenticated
  using (user_id = (select auth.uid()) and public.is_room_active(room_id));

alter publication supabase_realtime add table public.set_logs;
